[jnyz-app/server]2024/03/12 - 20:59:44.660	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_user.go:58	登陆失败! 用户不存在或者密码错误!	{"error": "record not found"}
[jnyz-app/server]2024/03/12 - 21:25:19.170	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/12 - 21:25:40.086	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/12 - 21:29:05.358	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/12 - 21:29:23.551	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_user.go:58	登陆失败! 用户不存在或者密码错误!	{"error": "db not init"}
[jnyz-app/server]2024/03/12 - 21:29:40.701	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:35	自动创建数据库失败!	{"error": "创建 [用户-权限] 关联失败, 未找到权限表初始化数据: missing dependent value in context", "errorVerbose": "missing dependent value in context\n创建 [用户-权限] 关联失败, 未找到权限表初始化数据\njnyz-app/server/source/system.(*initUser).InitializeData\n\t/home/amos/repo/jnyz-app/server/source/system/user.go:70\njnyz-app/server/service/system.MysqlInitHandler.InitData\n\t/home/amos/repo/jnyz-app/server/service/system/sys_initdb_mysql.go:88\njnyz-app/server/service/system.(*InitDBService).InitDB\n\t/home/amos/repo/jnyz-app/server/service/system/sys_initdb.go:125\njnyz-app/server/api/v1/system.(*DBApi).InitDB\n\t/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:34\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}
[jnyz-app/server]2024/03/12 - 21:30:31.940	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:24	已存在数据库配置!
[jnyz-app/server]2024/03/12 - 21:30:42.875	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/12 - 21:31:28.489	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/12 - 21:31:35.568	[31merror[0m	/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:35	自动创建数据库失败!	{"error": "创建 [用户-权限] 关联失败, 未找到权限表初始化数据: missing dependent value in context", "errorVerbose": "missing dependent value in context\n创建 [用户-权限] 关联失败, 未找到权限表初始化数据\njnyz-app/server/source/system.(*initUser).InitializeData\n\t/home/amos/repo/jnyz-app/server/source/system/user.go:70\njnyz-app/server/service/system.MysqlInitHandler.InitData\n\t/home/amos/repo/jnyz-app/server/service/system/sys_initdb_mysql.go:88\njnyz-app/server/service/system.(*InitDBService).InitDB\n\t/home/amos/repo/jnyz-app/server/service/system/sys_initdb.go:125\njnyz-app/server/api/v1/system.(*DBApi).InitDB\n\t/home/amos/repo/jnyz-app/server/api/v1/system/sys_initdb.go:34\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}
[jnyz-app/server]2024/03/12 - 21:31:38.726	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
[jnyz-app/server]2024/03/12 - 21:34:26.147	[31merror[0m	/home/amos/repo/jnyz-app/server/core/server.go:54	accept tcp [::]:9999: use of closed network connection
